DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ACCOUNTS;
DROP TABLE IF EXISTS TRANSACTION;
drop sequence IF EXISTS SQ_USER;
drop sequence IF EXISTS SQ_ACCOUNT;

create sequence SQ_USER;
create sequence SQ_ACCOUNT;

CREATE TABLE USERS (
  ID INT NOT NULL,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  SSN INT(64) NOT NULL ,
  REGISTRATION_ID VARCHAR(20),
  IS_ACTIVE BOOLEAN,
  constraint PK_CUSTOMER PRIMARY KEY (ID)
);

CREATE TABLE ACCOUNTS (
  ID INT NOT NULL,
  PIN SMALLINT NOT NULL,
  BALANCE DECIMAL,
  IS_ACTIVE BOOLEAN,
  constraint PK_ACCOUNTS PRIMARY KEY (ID)
);


/*CREATE TABLE TRANSACTION (
  ID INT AUTO_INCREMENT,
  TRANSACTION_DATE DATE,
  DESCRIPTION VARCHAR(64),
  TRANSACTION_TYPE VARCHAR(64),
  STATUS VARCHAR(64),
  AMOUNT DECIMAL(64),
  PRIMARY KEY (ID)
);*/
